server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  data:
    redis:
      repositories:
        enabled: false
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: HEo6bCSRjFCaJeRYTuFHEA4VnAxqVL2E
            client-secret: EO5J5r192a0kJnfMOYsOtnXgRJzndT2vZ-91IdWUQwtQKMju_5Fo_IopFG8838xe
            scope: openid, email, profile, offline_access, Customer, Admin
            authorization-grant-type: authorization_code  # âœ… Ensure it's `authorization_code`
            redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
            #client-authentication-method: client_secret_basic
        provider:
          auth0:
            issuer-uri: https://dev-hitesh-indian.us.auth0.com/
            jwk-set-uri: https://dev-hitesh-indian.us.auth0.com/.well-known/jwks.json
      resourceserver:
        jwt:
          issuer-uri: https://dev-hitesh-indian.us.auth0.com/

auth0:
  audience: https://customer-api/

management:
  tracing:
    enabled: true   # or false if you want to disable tracing entirely
  zipkin:
    enabled: false